# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Comment environment in PR

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  comment_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ””
        uses: actions/checkout@v2
      
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: ${GITHUB_REF##*/}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}